export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_CLOTHING_PRODUCT = 'GET_CLOTHING_PRODUCT';
export const GET_ACCESSORIES_PRODUCT = 'GET_ACCESSORIES_PRODUCT';
export const GET_CART_PRODUCT = 'GET_CART_PRODUCT';
export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';